"""added image column in products table

Revision ID: c901547e81d9
Revises: bd13ddc266c3
Create Date: 2025-03-08 15:25:00.456429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c901547e81d9'
down_revision = 'bd13ddc266c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_image'), ['image'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_image'))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
